model: # add base config
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.text_ddpm.TextDiffusionRounding
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: input_ids
    cond_stage_key: cond_input_ids
    text_length: 64
    channels: 768
    cond_stage_trainable: false
    first_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 1
    # uncond_training_ratio: 0.1
    unconditional_guidance_scale: [1.5, 2, 5, 10, 50]
    use_ema: False
    parameterization: x0
    l_simple_weight: 1.
    original_elbo_weight: 1.
    nll_weight: 0.001

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 10000 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: ldm.modules.diffusionmodules.textmodel.TransformerModel
      params:
        in_channels: 768
        out_channels: 768
        model_channels: 512
        config_name: roberta-base
        cond: cross
        cond_config_name: roberta-base
        input_projection: True
        output_projection: True

    first_stage_config:
      target: ldm.models.text_embedder.TextEmbedderLMHead
      params:
        embedding_ckpt_path: /zhangpai21/workspace/zwd/ckpts/roberta-base/1/mp_rank_00_model_states.pt
        vocab_size: 50265
        hidden_size: 768
        sample_length: 64
    cond_stage_config: __is_first_stage__

tokenizer_type: 'roberta-base'

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    num_workers: 16
    wrap: false
    train:
      target: ldm.data.textdataset.QuasarTDataset
      params:
        path: /zhangpai21/workspace/zwd/seq2seq_data/quasar/data/datasets/quasart/train.json
        sample_length: 64
        cond_length: 64
    test:
      target: ldm.data.textdataset.QuasarTDataset
      params:
        path: /zhangpai21/workspace/zwd/seq2seq_data/quasar/data/datasets/quasart/test.json
        sample_length: 64
        cond_length: 64
        num_shards: 8
        shard_id: 7

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 10000
  callbacks:
    text_logger:
      target: main.TextLogger
      params:
        batch_frequency: 10000
        max_texts: 64
        increase_log_steps: False
        log_first_step: False
        log_texts_kwargs:
          ddim_steps:
          N: 64
          unconditional_guidance_scale: [1.5, 2, 5, 10, 50]

  trainer:
    benchmark: True
    max_steps: 500000
  